### ISSUE TITLE
Can't login even after resetting password

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-online#10]
I've reset my password a couple times, and received reset emails just fine. However, when I try to login, it doesn't work. I'm using 1Password to generate my passwords. The first one had a period in it (`u7kWNv.jMxwBV}wH`), the current one has no symbols in it.

**Comment by jdubois** [comment]
Matt, that's because you use your email address instead of your user name (I just read the audit logs).
That's a big UX issue we have from the start, that comes from JHipster itself

**Comment by jdubois** [comment]
And I just added a more explicit error message
