### ISSUE TITLE
Registration process seems to have a bug

### ISSUE THREAD

**Issue by dependencyinjection81** [jhipster/jhipster-online#101]
I tried to register and burned two email adresses.
The issue is that I don't get a confirmation on any of the e-mail adresses.
First I thought for any reason it doesn't saved my registration and just tried to 
login with my credentials and expected the login-page will redirect me to a page that tell me to verify my account first. But it just say that my credentials are wrong.
When I go to forget my password, it says there is no account with that email but when i try to make a new account it says this email is already in use. That way i burned two email addresses of mine and you have two more kartei corpse in your database i think.

Best regards and hopefully you manage to make the sign-up process work

**Comment by KTurbo** [comment]
I have the same problem. I, too, used two different email addresses.

**Comment by jdubois** [comment]
Yes that's because we use the free tier from mailgun (the service is free, so no money...), and they are blocked by several mail providers like hotmail...
Please give me your usernames and I'll activate your accounts manually when I get time.

**Comment by KTurbo** [comment]
I believe I used alexander.lindstrom as my username. If it was not what I used (cannot remember since I registered twice) it is the one where the e-mail address matches that name. Thank you!

**Comment by jdubois** [comment]
Oh no, in fact the mail server is down and we have hundreds of people who could not register :-(

I'll do my best but I don't have time at the moment

**Comment by alexanderlindstrom** [comment]
Oh, that's bad. 😮 I hope you get it sorted out soon. Drop us a line here so we can try it out once you've fixed it.

**Comment by jdubois** [comment]
Thanks a lot for reporting the issue, as we have hundreds of people who didn't!
Anyway: restarted the server, so you should be able to register again using the same email address, and you'll get the mail.

I'll focus on removing the email registration, that's the best way not to have this ever again.

**Comment by jdubois** [comment]
I have disabled email registration, so now you can login easily!

**Comment by alexanderlindstrom** [comment]
Good work. Though I am not able to login with my registered user names and I cannot re-register since the e-mail is already in use. I'm not sure what to do atm. 😕

**Comment by jdubois** [comment]
Oh I see.... I activated manually!
Otherwise non activated emails will be deleted after 2 days.

**Comment by alexanderlindstrom** [comment]
There we go. Thank you so much!
