### ISSUE TITLE
Build issue with Jhipster online

### ISSUE THREAD

**Issue by amalkurup** [jhipster/jhipster-online#104]
I am trying to deploy jhipster online on Openshift using docker strategy, but I am facing the below build issue related to maven. Can anyone point on this 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jhonline: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.7.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.maven.plugins:maven-compiler-plugin:jar:3.7.0 -> org.apache.maven:maven-plugin-api:jar:3.0 -> org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2 -> org.codehaus.plexus:plexus-component-annotations:jar:1.6: Failed to read artifact descriptor for org.codehaus.plexus:plexus-component-annotations:jar:1.6: Could not transfer artifact org.codehaus.plexus:plexus-component-annotations:pom:1.6 from/to central (https://repo.maven.apache.org/maven2):  Connection timed out (Read failed)

**Comment by pascalgrimaud** [comment]
can you, at least, tell us what command you used ? so we can try to reproduce

**Comment by amalkurup** [comment]
oc new-app https://github.com/jhipster/jhipster-online

**Comment by jdubois** [comment]
I'm sorry but I have never used this command, I don't even know what it does, so I would be quite surprised this works out of the box.

I'm not sure this should be a bug report, you're using a tool we have not even tested at all.

**Comment by amalkurup** [comment]
Can you point me on the steps to build image of jhipster online and push to dockerhub

**Comment by jdubois** [comment]
@amalkurup there is one which is automatically build on https://hub.docker.com/r/jhipster/jhipster-online/

It uses https://github.com/jhipster/jhipster-online/blob/master/Dockerfile to generate the image, so if you want to do your own image (if you modify something), that should also be easy to do.

**Comment by amalkurup** [comment]
@jdubois Thanks for the pointer. I am closing this issue, as it's resolved
