### ISSUE TITLE
JHipster problem when try to change password in web site

### ISSUE THREAD

**Issue by laidani** [jhipster/jhipster-online#105]
According to my question in [stackoverflow](https://stackoverflow.com/questions/55552610/jhipster-problem-when-try-to-change-password-in-web-site), I have a problem when I click to [Account then **Did you forget your password?**](https://start.jhipster.tech/#/reset/request) I get this error :

> Emails are disabled on this server! You will need to ask an administrator to provide you a password reset link.

**Comment by atomfrede** [comment]
@laidani We had huge problems with our mail provider to deliver emails to certain domains. Therefore mails are disabled for jhipster online for the moment. @jdubois will help you as soon as he has time

**Comment by jdubois** [comment]
Our biggest issue is that we don't want to spend $100 per month just for sending a few emails :-)
I need a couple of hours to recode this part, but I just don't have any free time at the moment. 
In the meantime, if you want me to reset your password or delete your account, just give me your email address and I'll do it when I have time.

**Comment by laidani** [comment]
Thank you @atomfrede for me I remebered my password, and I can use jhipster very well, the issue is for the future users

**Comment by laidani** [comment]
@jdubois as I mentioned in the last comment and in my question in stackoverflow, which is the way yo contact you, do you want every user to send you a request via github? For me I can't put my email in public, where every one can see it.
Thank you for your help any way.

**Comment by jdubois** [comment]
Hi @laidani - I did a new release, and now you should be able to reset your password!
Now the email provider is only used to reset passwords, so that's not as bad as before if it fails

**Comment by laidani** [comment]
Hi @jdubois, thank you, I try it and it worked perfectly :)
