### ISSUE TITLE
UNIQUE Constraint in JHipster online

### ISSUE THREAD

**Issue by iDisturb** [jhipster/jhipster-online#115]
Hello, I cannot find the constraint UNIQUE in JHipster online, is it not supported, I have read that it is but probably it's not updated in JHipster JDL Studio

**Comment by SudharakaP** [comment]
@iDisturb : Sorry for being so late on addressing this issue; but this is now addressed through the pull request https://github.com/jhipster/jdl-studio/pull/88. 

Related issue; https://github.com/jhipster/jdl-studio/issues/60. 

Therefore I am closing this. :smile:
