### ISSUE TITLE
Callback for GitHub synchronization is wrong

### ISSUE THREAD

**Issue by kaitlin-farr** [jhipster/jhipster-online#12]
When I access https://start.jhipster.tech/#/github and attempt to synchronize my GitHub account, the callback after I've accepted the permissions on GitHub tries to take me to http://jhipster.julien-dubois.com/#/github/callback/<token here>, but this defaults to an Apache2 Ubuntu Default Page.

My workaround was to manually replace jhipster.julien-dubois.com with https://start.jhipster.tech in the url I pasted above, and it was able to successfully synchronize my account.

**Comment by jdubois** [comment]
Oh you are right, thanks a lot!!!

**Comment by jdubois** [comment]
Just corrected it, can you try again?

**Comment by jdubois** [comment]
At least it now works for me, that was a really stupid bug!!!

@kaitlin-farr thanks a lot, and if you can try again I would really appreciate it

**Comment by kaitlin-farr** [comment]
Now, it works for me, too!

**Comment by jdubois** [comment]
Thank you so much!
