### ISSUE TITLE
while creating new jdl model,getting error page,

### ISSUE THREAD

**Issue by Dap555** [jhipster/jhipster-online#125]
Hi ,
please find below template details:

C:\jhipster\jhipster\jhipster-online-master\jhipster-online-master>jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhonline@2.4.0 C:\jhipster\jhipster\jhipster-online-master\jhipster-online-master
`-- generator-jhipster@5.0.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.jhipster.online"
    },
    "jhipsterVersion": "5.0.2",
    "baseName": "jhonline",
    "packageName": "io.github.jhipster.online",
    "packageFolder": "io/github/jhipster/online",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "cacheProvider": "ehcache",
    "enableHibernateCache": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity JdlMetadata (jdl_metadata) {
  key Long required,
  name String,
  isPublic Boolean
}
entity SubGenEvent (sub_gen_event) {
  year Integer,
  month Integer,
  week Integer,
  day Integer,
  hour Integer,
  source String,
  type String,
  event String,
  date Instant
}
entity EntityStats (entity_stats) {
  year Integer,
  month Integer,
  week Integer,
  day Integer,
  hour Integer,
  fields Integer,
  relationships Integer,
  pagination String,
  dto String,
  service String,
  fluentMethods Boolean,
  date Instant
}
entity Language (language) {
  isoCode String
}
entity GeneratorIdentity (generator_identity) {
  host String,
  guid String
}
entity UserApplication (user_application) {
  name String,
  shared Boolean,
  sharedLink String,
  userId String,
  configuration TextBlob
}
entity YoRC (yo_rc) {
  jhipsterVersion String,
  creationDate Instant,
  gitProvider String,
  nodeVersion String,
  os String,
  arch String,
  cpu String,
  cores String,
  memory String,
  userLanguage String,
  year Integer,
  month Integer,
  week Integer,
  day Integer,
  hour Integer,
  serverPort String,
  authenticationType String,
  cacheProvider String,
  enableHibernateCache Boolean,
  websocket Boolean,
  databaseType String,
  devDatabaseType String,
  prodDatabaseType String,
  searchEngine Boolean,
  messageBroker Boolean,
  serviceDiscoveryType Boolean,
  buildTool String,
  enableSwaggerCodegen Boolean,
  clientFramework String,
  useSass Boolean,
  clientPackageManager String,
  applicationType String,
  jhiPrefix String,
  enableTranslation Boolean,
  nativeLanguage String,
  hasProtractor Boolean,
  hasGatling Boolean,
  hasCucumber Boolean
}
service JdlMetadata, SubGenEvent, EntityStats, Language, GeneratorIdentity, UserApplication, YoRC with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.21.0.windows.1

node: v10.16.0

npm: 6.9.0

yeoman: 3.1.0

yarn: 1.17.3

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b

Congratulations, JHipster execution is complete!

I am understanding that i keep on asking help for jhipster-online configuration in my local,
I couldn't able to understand some flow, thats why i am asking those many questions, I think this is last step to make it up locally, 
currently i am stuck with creating new jdl using ui, when , I am going to design entity page, 
there is option to create new jdl model, when i am clicking on this button , I am getting error page, with message 

Your request cannot be processed
Sorry, an error has occurred.

Status: Not Found (Not Found)
Message: Not Found
Other things to try:
Search localhost:9000:
Please find below logs as well as attached screen where , i am stuck, please hint me here, i couldn't able to debug this screen.Hope this time you will not block me ,  i sending template details as well ,

logs;
2019-08-08 10:25:59.327 DEBUG 15436 --- [ XNIO-2 task-19] i.g.j.online.web.rest.GitResource        : Git configuration : GitConfigurationDTO{githubHost='https://github.com', githubClientId='null', githubAvailable=false, gitlabHost='https://gitlab.com', gitlabRedirectUri='null', gitlabClientId='null', gitlabAvailable=false, githubConfigured=false, gitlabConfigured=false}
2019-08-08 10:25:59.328 DEBUG 15436 --- [ XNIO-2 task-19] i.g.j.online.aop.logging.LoggingAspect   : Exit: io.github.jhipster.online.web.rest.GitResource.getGitlabConfig() with result = <200 OK,GitConfigurationDTO{githubHost='https://github.com', githubClientId='null', githubAvailable=false, gitlabHost='https://gitlab.com', gitlabRedirectUri='null', gitlabClientId='null', gitlabAvailable=false, githubConfigured=false, gitlabConfigured=false},{}>
2019-08-08 10:26:02.949 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.online.aop.logging.LoggingAspect   : Enter: io.github.jhipster.online.web.rest.JdlMetadataResource.getAllJdlMetadata() with argument[s] = []
2019-08-08 10:26:02.951 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.o.web.rest.JdlMetadataResource     : REST request to get all JdlMetadata
2019-08-08 10:26:02.955 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.online.aop.logging.LoggingAspect   : Enter: io.github.jhipster.online.service.UserService.getUser() with argument[s] = []
2019-08-08 10:26:02.962 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.online.aop.logging.LoggingAspect   : Exit: io.github.jhipster.online.service.UserService.getUser() with result = User{login='RaviGithub555', firstName='Ravi', lastName='Kumar', email='ravi.scitm@gmail.com', imageUrl='null', activated='true', langKey='en', activationKey='52892693814623479987'}
2019-08-08 10:26:02.965 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.online.aop.logging.LoggingAspect   : Enter: io.github.jhipster.online.service.JdlMetadataService.findAllForUser() with argument[s] = [User{login='RaviGithub555', firstName='Ravi', lastName='Kumar', email='ravi.scitm@gmail.com', imageUrl='null', activated='true', langKey='en', activationKey='52892693814623479987'}]
2019-08-08 10:26:02.966 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.online.service.JdlMetadataService  : Request to get all JdlMetadata for user RaviGithub555
2019-08-08 10:26:02.969 DEBUG 15436 --- [ XNIO-2 task-20] i.g.j.online.aop.logging.LoggingAspect   : Exit: io.github.jhipster.online.service.JdlMetadataService.findAllForUser() with result = []

![designEntity](https://user-images.githubusercontent.com/53740328/62676188-902cdb00-b9c7-11e9-8755-ddc31bfb70ed.GIF)
![jhipsterOnline_jdl](https://user-images.githubusercontent.com/53740328/62676189-902cdb00-b9c7-11e9-9ead-74a97da2353e.jpg)

**Comment by pmverma** [comment]
I have never run it locally though but jdl studio is another project and you will need to integrate it I think.
https://github.com/jhipster/jdl-studio

The README file does not cover the jdl-studio integration part but hey, it is open source and the whole repository is available for free.

Try to check the PRs for jdl-studio integration.

**Comment by pascalgrimaud** [comment]
Sorry @Dap555, but Github is used as bug tracker, not for question or help.

If you need free help, use StackOverFlow instead. 
If you need professionnal help, you can contact Ippon Technologies.

If you don't know how to configure the project, just use directly https://start.jhipster.tech/#/

So plz, stop spamming us.

**Comment by Dap555** [comment]
Thanks for your response, 
But here I am not asking help, here this is bug that jdl-studio not working with jhipster-online, as I already explained you, if really this will not work with jhipster-online in local, then please mention the same in readme instruction, people will try this, why people will unwantedly struggle a lots this  jdl-studio make it up in local.
So please tell me this is not a bug?

**Comment by pascalgrimaud** [comment]
Not a bug. I took me 2min to clone and configure the project.
See my screenshot:

![Capture d’écran de 2019-08-08 11-37-22](https://user-images.githubusercontent.com/9156882/62692547-20235280-b9d1-11e9-8dff-2d0f675e0ef4.png)

![Capture d’écran de 2019-08-08 11-37-30](https://user-images.githubusercontent.com/9156882/62692561-24e80680-b9d1-11e9-8931-11286ee03a95.png)

**Comment by Dap555** [comment]
Thanks pascal,
I am also doing all the same step, 
1.getting clone from git
2.yarn install and start.
3.making db up. in db also all table are created itself,
4.at last giving mvnw command,
5. application is also up, as I show you, file also downloading ,
but while creating new jdl its giving me error page, there is definitely some configuration missing from my end, please let me know any instruction I am missing , I not going beyond readme instruction.
If you want I will share you all the details but its surprise for me why it is not working for me.

**Comment by Dap555** [comment]
Hope, I will get response at your end for this issue with jhister online create new jdl model
________________________________
