### ISSUE TITLE
Not able to generate sample jhipster Application on gitHub

### ISSUE THREAD

**Issue by JalajChawla** [jhipster/jhipster-online#126]
I tried generating the application on GitHub on the given URL https://start.jhipster.tech/#/generate-application but it shows no error and keeps showing a loading screen.

PFA the screen I am getting though I am able to download the zip file
![Screenshot from 2019-09-08 12-37-22](https://user-images.githubusercontent.com/52110481/64484838-af708f80-d235-11e9-9680-6b8c27f54787.png)

**Comment by jdubois** [comment]
Thanks a lot @JalajChawla !!! I confirm the issue, so really thank you for pointing this out!!

@PierreBesson @pascalgrimaud I have no idea what happened, I just restarted the server and now it works.

What has happened in the past was that the process generating the app got stuck (typically there was a question being asked at the prompt, so the process was waiting for the answer), but that should have been "solved" now as processes should be killed after a timeout.

**Comment by PierreBesson** [comment]
Yes the generation process is based on the jhipster "interractive" CLI so it succeptible to problems like this. I think we should migrate the process to "non interactive" JDL generation at some point.
