### ISSUE TITLE
Provide IDE integration based on the API

### ISSUE THREAD

**Issue by danielpetisme** [jhipster/jhipster-online#13]
Now that we can generate a jhipster project using an API, we could imgaine to propose wizards for the most common IDEs to create a jhipster project.
Starting point of the discussion: https://twitter.com/pibesson/status/900454148998606848

Based on [@jdubois comment](https://twitter.com/java_hipster/status/900463313020223489) most of the logic is in the front-end app.

**Comment by jdubois** [comment]
Yes the annoying part is that there is some logic in what is being sent: for example, only microservices can be created without a database...
This logic has been implemented in the generator, and I recoded it in the Angular form. Coding it one more time is really annoying, and it also adds maintenance.
Aside from this part, it should be really easy to do: in the Angular form I just create the `.yo-rc.json` file and POST it to the server. Depending on the URL, it's either created on GitHub, or downloaded.

**Comment by PierreBesson** [comment]
For this feature, it would be good to enable swagger, so that the docs will show up here: https://start.jhipster.tech/swagger-ui/index.html

**Comment by jdubois** [comment]
As you can see from https://github.com/ippontech/blog-usa/pull/40 it's already easy to do, but you need to have an account.
(btw @colameo this should be interesting for you)
At the moment I still want to have people to create a registered account, so we don't have people who spam the project. I want good statistics and real users.
