### ISSUE TITLE
Failed to sign in! 

### ISSUE THREAD

**Issue by erwinyo87** [jhipster/jhipster-online#14]
When i register, im using my email as username, and already activate the email below
-------------------------------------------------
Dear erwin.yo87@gmail.com

Your JHipster Online account has been created, please click on the URL below to activate it:
--------------------------------------------------
after activate, i login to jhipster-online then error:

Failed to sign in! 
Did you use your username, and not your e-mail address? 
Please check your credentials and try again.

**Comment by jdubois** [comment]
Oh I see, you're using your email address both for email and username - why not :-)

That shouldn't make any difference, but I do see the login errors - are you sure you are using the right password? Your account is correctly activated, everything should work

**Comment by erwinyo87** [comment]
ah isee, i misspell my password,

i just seeing that response: 
Failed to sign in! 
Did you use your username, and not your e-mail address? 
Please check your credentials and try again.

so i thought my username is not working
thanks jdubois

**Comment by jdubois** [comment]
Great, thanks - and don't hesitate to send feedback!
