### ISSUE TITLE
Cannot resolve com.microsoft.sqlserver:mssql-jdbc:8.1.0.jre8

### ISSUE THREAD

**Issue by mrsegen** [jhipster/jhipster-online#141]
I've freshly generated an app using https://start.jhipster.tech/.

When opening the unzipped project in IntelliJ, the initial attempt to sync/index, includes resolving dependencies, which results in: `Cannot resolve com.microsoft.sqlserver:mssql-jdbc:8.1.0.jre8`

Now, `com.microsoft.sqlserver:mssql-jdbc:8.1.0.jre8` doesn't exist as of this writing. Instead it's `com.microsoft.sqlserver:mssql-jdbc:8.1.0.jre8-preview`.

**Comment by mrsegen** [comment]
By adding the previous version, I got it running.

In other words I changed the following in pom.xml ...
```
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
        </dependency>
```
... to ...
```
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>7.4.1.jre8</version>
        </dependency>
```

**Comment by agaspardcilia** [comment]
This looks like it is an issue with the [generator](https://github.com/jhipster/generator-jhipster) itself and not JHipster Online. 

I'm closing this since it's unfortunately not the right place for that (Thanks for giving a fix tho).
