### ISSUE TITLE
The generated app doesn't show the menu Languages 

### ISSUE THREAD

**Issue by yfain** [jhipster/jhipster-online#15]
Overview of the issue

The online-generated monolithic app doesn't show the menu Languages, while the locally-generated app does.

Motivation for or Use Case

The online-generated app should be consistent with locally-generated app in terms of the internationalization support.

Reproduce the error

Download and run the newly generated monolithic app from http://bit.ly/2gmzZN7

JHipster info

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

JHipster Version(s)

nyc-1@0.0.0 /Users/yfain11/Downloads/nyc1
└── generator-jhipster@4.7.0 

JHipster configuration, a .yo-rc.json file generated in the root folder

.yo-rc.json file
JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory

JDL entity definitions
Environment and Tools

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.1

node: v8.1.3

npm: 5.3.0

yeoman: 2.0.0

yarn: 0.27.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

Execution complete

Browsers and Operating System

MAC OS 10.11.6, Chrome 60

[ x] Checking this box is mandatory (this is just to show you read everything)
 @deepu105
 Member

**Comment by PierreBesson** [comment]
Thanks for the report @yfain. I found the bug ! :smiley:

I regenerated your nyc1 app with `jhipster --force` and there was no difference at all. So no issue on this side, JHipster Online is correctly generating the app from the yo-rc which was provided.

However when I started the app, indeed you cannot change the language, so I suspected that there is an issue with the `.yo-rc.json` file generated by JHipster Online.
**yo-rc generated by JHipster online**
```
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "gitHubOrganization": "",
    "baseName": "nyc1",
    "packageName": "io.github.jhipster.application",
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "enableTranslation": false,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ],
    "clientFramework": "angularX",
    "jhipsterVersion": "4.7.0",
    "packageFolder": "io/github/jhipster/application",
    "jwtSecretKey": "3e65d5917f943b623206179b204def4a5b06452a",
    "jhiPrefix": "jhi"
  }
}
```

**yo-rc generated by the CLI**
```
{
  "generator-jhipster": {
     "promptValues": { //<--  LOOK HERE
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.7.0",
    "baseName": "nyc1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "9233dd865c5a9f0d9808f36747897ff71adb5c2b",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}
```
Notice the `promptValues.nativeLanguage` that is missing. @jdubois can you give me access to jhipster-online code so I can fix the bug ?

**Comment by ruddell** [comment]
@PierreBesson Shouldn't we fix the generator to use the `nativeLanguage` we already store ourselves instead of `prompts.nativeLanguage`?

**Comment by PierreBesson** [comment]
@rudell, I don't know much about how the .yo-rc is generated by the cli so if you think this can be fixed in the generator then please go ahead.

**Comment by jdubois** [comment]
Yes you are both right:

- there's probably an issue in the generated .yo-rc.json
- but the cli should also be more robust and solve this



Le 30 août 2017 19:02, "Pierre Besson" <notifications@github.com> a écrit :

@rudell, I don't know much about how the .yo-rc is generated by the cli so
if you think this can be fixed in the generator then please go ahead.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/jhipster-online/issues/15#issuecomment-326143050>,
or mute the thread

**Comment by deepu105** [comment]
I think the prompt Value section is coming from yeoman somehow(it started
to appear after our upgrade ro yeoman 1.0), may be for items having a
default value?
But in either case that part should not matter and should not be used for
config. I thought it was something yeoman used internally thats why didn't
bother about it. I didn't know it was causing issue. It might be a yeoman
issue as well.

**Comment by jdubois** [comment]
Not sure about this: @PierreBesson in fact you have no translation in the first file because you have `"enableTranslation": false` int it... So that's normal.
I'm doing more tests.

**Comment by jdubois** [comment]
In fact this value is also set to `false` in the test `.yo-rc.json`, so that's "normal". But we should improve the UI, and not show any language if "no" is selected.
