### ISSUE TITLE
JHipster online Forgot Password not working

### ISSUE THREAD

**Issue by akahky** [jhipster/jhipster-online#16]
JHipster online forgot password dialog is not working correctly, you can enter your email address and press Reset then you will not get any email about the password changes and the email address field will not be cleared.

**Comment by jdubois** [comment]
I do see some "reset password" e-mails in the logs, so I think this is working correctly... Can you give me your login name, so I test just for you?

**Comment by jdubois** [comment]
Closing as we got no answer.
