### ISSUE TITLE
JDL studio not available

### ISSUE THREAD

**Issue by gco-nb** [jhipster/jhipster-online#171]
Hello,
The URL : https://start.jhipster.tech/jdl-studio/ gives an error message not found.
Your request cannot be processed
Sorry, an error has occurred.

Status: Not Found (Not Found)
Message: Not Found

**Comment by pascalgrimaud** [comment]
Indeed, I can confirm
Thanks for reporting the issue

**Comment by pascalgrimaud** [comment]
https://github.com/jhipster/jhipster-online/blob/master/package.json#L130 is supposed to work...

@deepu105 : can you confirm ? is it the correct command as in my local env, it doesn't work. Maybe should I copy/paste manually ?

**Comment by vishal423** [comment]
@pascalgrimaud, did you checkout git submodules before build and deployment? Above command is to synchronize to take latest code from `jdl-studio`

**Comment by pascalgrimaud** [comment]
@vishal423 : no I didn't do it. I launched `mvn verify -Pgcp` only

**Comment by SudharakaP** [comment]
@pascalgrimaud : Yeah as @vishal423 mentioned I don't think we used the `recursive` step in our deployment; `git submodule update --init --recursive`.

**Comment by vishal423** [comment]
@pascalgrimaud , @SudharakaP , you just need to take checkout of git submodule and the normal build will take care of integration. You can checkout submodules during clone with `git clone --recurse-submodules` or post that with `git submodule update --init --recursive`

Let me know if you face any issues while doing it.

**Comment by deepu105** [comment]
Sorry just saw this. yes Vishal is right, the command just pulls latest
code once you have sub module setup.

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
It should be ok: https://start.jhipster.tech/jdl-studio/
I'm closing this
