### ISSUE TITLE
JDL login page doesn't work

### ISSUE THREAD

**Issue by obwaze** [jhipster/jhipster-online#173]
Hi team,

Access to my account on https://start.jhipster.tech/ doesn't work since yesterday.
Authentication seem works but there is a redirect on the home page after login.

**Comment by pascalgrimaud** [comment]
hi @obwaze 
Can you try to log into your browser in private mode ?

We did an upgrade of JHipster Online yesterday, from 5.0.2 to 6.8.0
We needed to change the JWT secret, to use a base64, so if you checked "remember me" when you log in, it could explain

**Comment by obwaze** [comment]
Hi @pascalgrimaud 

Thank for your reply.
Effectively it's work in private mode.
The jdl-studio works also.

Thanks again for your actions
