### ISSUE TITLE
Can not sign in

### ISSUE THREAD

**Issue by BugHunterPhilosopher** [jhipster/jhipster-online#181]
Hi there,

Since yesterday I can not log in to the JDL studio anymore, hence I can't edit my entities. I mean : the sign in modal window appears, I can submit my credentials, but then the modal window disappears and I'm still not logged in.

What shall I do, please? I'd like to edit my old models and I wish I'm not forced to register again and reimport them.

Regards

**Comment by BugHunterPhilosopher** [comment]
All right! Feel free to ask for more tests. Cheers!

**Comment by vishal423** [comment]
can you check solution of #173

**Comment by BugHunterPhilosopher** [comment]
Yep, that does the trick, thanks! Both private mode and remember me allow me to log in.

Cheers!
