### ISSUE TITLE
Unable to reset password in jhipster online

### ISSUE THREAD

**Issue by yashjit** [jhipster/jhipster-online#187]
No mail delivered to my registered email address.

**Comment by SudharakaP** [comment]
@yashjit : For password resets we do not send emails. When you click on `Account -> Password` and enter your new password and click save you should see a success message and that's it. Were you able to do this? :smile:

**Comment by SudharakaP** [comment]
@yashjit : This is probably related to the generation issue we are currently having. For now I've restarted the server. Can you try again?

**Comment by SudharakaP** [comment]
This is actually related to https://github.com/jhipster/jhipster-online/pull/175 since we haven't fully enabled the email service it seems.
