### ISSUE TITLE
"No database" option visibility

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-online#189]
The "No database" option visibility condition doesn't match the one in the CLI. In particular it's not available for monolith.

CLI : https://github.com/jhipster/generator-jhipster/blob/4673fe4397a314f157f8919da0c2395fe05cd9d2/generators/server/prompts.js#L202

JH Online : https://github.com/jhipster/jhipster-online/blob/6af0fafe1503a82ac0fcbc368f4be2b84374d0a2/src/main/webapp/app/home/generator/generator.component.html#L113

**Comment by SudharakaP** [comment]
@cbornet : Done. :+1: Let me know if you see any issues.
