### ISSUE TITLE
new features we will release,some my suggestion

### ISSUE THREAD

**Issue by shiLinTan** [jhipster/jhipster-online#19]
the online generator is building successful ,so i can do not to install some busy software in my person computer ,note that my system is window7 64bit now,so ?in some day ago ,in order to use it ,i must to rebuild my pc,now is not necessery,seconde is the oncline JDL-Studio is builded successful,so i think sometimes we need to improve the  online generator to import jh file,very hope it as soon as vell come to us.thanks

**Comment by jdubois** [comment]
Yes I'd love to have JDL integration in JHipster Online. Unfortunately we don't have the time to code this at the moment, but I guess that would be just a couple of days of code.
I'm closing this as yes, we will do it!!!
