### ISSUE TITLE
Login / GitHub access

### ISSUE THREAD

**Issue by rdmueller** [jhipster/jhipster-online#2]
Great tool, but why do I need to create an account _and_ give access to github?
Would the github oauth access not also work as login?

And a version without the need for access to the github repositories (download as zip) would be great!

**Comment by jdubois** [comment]
In fact you are answering your own question :-)
As we would like to propose downloads, we can't make GitHub authentication mandatory. 
Another reason is that it was quicker to code like this, as JHipster generates the whole authentication mechanism.

**Comment by rdmueller** [comment]
...but a GitHub auth without repo access or another social login would be great. I hate having to create another account :-)
But I do understand the "quicker to code" argument :-)
Feel free to close this ticket...
