### ISSUE TITLE
not able to sign in

### ISSUE THREAD

**Issue by KassemAlsayed** [jhipster/jhipster-online#20]
just registered (kassem.Ali@innovapost.com), but not able to sign in. getting:

_Failed to sign in! 
Did you use your username, and not your e-mail address? 
Please check your credentials and try again._

Thanks

**Comment by jdubois** [comment]
Yes, as said in the error message `Did you use your username, and not your e-mail address?` -> I see in the logs you used your e-mail address, and not your username. So you should use your username.
