### ISSUE TITLE
Integrate SonarCloud

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/jhipster-online#202]
I would like to integrate [SonarCloud](https://sonarcloud.io/) to this project instead of CloudQL. It seems CloudQL only does security vulnerabilities and although I opened a PR before for that (https://github.com/jhipster/jhipster-online/issues/192), I now think SonarCloud might be more comprehensive and also it will be consistent with the generator. 

@pascalgrimaud : Would you be able to either add SonarCloud GitHub integration to this repo or add me to the SonarCloud jhipster org so that I can do that? I can see SonarCloud app here (https://github.com/jhipster/jhipster-online/settings/installations), but probably it's not configured.

**Comment by pascalgrimaud** [comment]
I will take care of this. I was too busy today, just give time :)

**Comment by SudharakaP** [comment]
> I will take care of this. I was too busy today, just give time :)

No problem, take your time. :+1:

**Comment by pascalgrimaud** [comment]
@SudharakaP : it should be OK. I created the project at SonarCloud https://sonarcloud.io/organizations/jhipster/projects and added the SONAR_TOKEN in secrets

**Comment by pascalgrimaud** [comment]
@SudharakaP : I added you to JHipster Organization as member too. You should be able to manage it. Tell me if you encounter some problem.

**Comment by SudharakaP** [comment]
@pascalgrimaud : Thanks a lot. Will take a look. :smile:
