### ISSUE TITLE
Translation and additional language bug

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-online#21]
When you activate translation support and choose a main language without selecting it in additional languages, no translation is found when running the app.

For example, I chose "French" as my main language and "English" as additional language, only "en" is present as languages in `.yo-rc.json`, see https://github.com/hdurix/testOnline/blob/master/.yo-rc.json#L28

The bug is not present in the basic generator as the main language is added to application languages (both "fr" and "en" are defined in `.yo-rc.json`), see https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-base.js#L2155

The algorithm should be the same, the main language should be added as a language even if this language is not selected in select box (or it should not appear at all or disabled in the select box as it means nothing).

**Comment by pascalgrimaud** [comment]
The bug has been reported here: https://github.com/jhipster/generator-jhipster/issues/6713

As I didn't watch this repository, I didn't notice it before.
Now, I wonder if the ticket should be opened here or at generator-jhipster

@hdurix : as it has been fixed, you can close it :)

**Comment by hdurix** [comment]
Thanks! Yes @jdubois told me he fixed the bug and I forgot to close it.

You're right, it's probably better to open the issues in generator-jhipster, especially with the current work to gather all the JHipster projects in the generator repository.
