### ISSUE TITLE
Login not working after new account creation

### ISSUE THREAD

**Issue by imadbougataya** [jhipster/jhipster-online#22]
Hi,

I have just created an account for JHipster online, at first try after activation, password not recognized. Changed the password and proceeded to login again, and again password not working.

I have been careful in typing the password, so there's got to be another problem there.

**Comment by jdubois** [comment]
Are you sure you used your username and not your e-mail?

**Comment by jdubois** [comment]
I just had a look in the logs and you used your e-mail address. You should use your username to log in.
This will be solved soon, you will be able to use both.
