### ISSUE TITLE
Incorrect version v6.9.0 instead of v6.10.1

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-online#228]
I just generated a new project at start.jhipster.tech :
https://github.com/pascalgrimaud/jhipster-sample-application200905

The version of generator-jhipster is v6.9.0 instead of v6.10.1

**Comment by SudharakaP** [comment]
@pascalgrimaud : Ah, yes, I missed updating this. Let me do that now. 😄
