### ISSUE TITLE
Registration mail delayed

### ISSUE THREAD

**Issue by gmarziou** [jhipster/jhipster-online#23]
Hi Julien,

I registered and it took 15 minutes or more before I received the registration confirmation mail, I did not measure time as I first thought that the mail was not sent.

I received mail at 12/12/2017 22:36 for gmarziou user, maybe you could compare with the date in logs.

**Comment by jdubois** [comment]
Yes I found you in the logs, this is because there was an error from the free.fr servers:

```
 "delivery-status": {
        "mx-host": "mx1.free.fr",
        "attempt-no": 1,
        "description": "",
        "session-seconds": 0.07130002975463867,
        "retry-seconds": 600,
        "code": 451,
        "message": "Local Error"
    }
