### ISSUE TITLE
JHOnline: improve UI

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-online#237]
##### **Overview of the issue**

The UI can be improved, because today, it's not really beautiful...
- check box
- select too long
- etc.

The `new` to statistic needs to be removed.
It has been long time ago...

##### **Motivation for or Use Case**

![jhipster-online-ui](https://user-images.githubusercontent.com/9156882/92997733-9ae46880-f515-11ea-9ad4-27fe4c919a92.png)

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ankitbeniwal** [comment]
Hey. I would like to work on this one.

**Comment by SudharakaP** [comment]
@ankitbeniwal : Thanks a lot. Sure, please feel free to suggest a PR. Some of the things we need to do here are; 

- [ ] Remove the `new` label in the statistics tabs
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/12435965/96459822-6a0fe700-11d7-11eb-8bd3-33a60e353fb9.png)
</details>

- [ ] Reduce the width of html select tags
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/12435965/96459887-785e0300-11d7-11eb-9847-d218e024e09f.png)
</details>

- [ ] Make the checkbox more nicer
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/12435965/96459918-83189800-11d7-11eb-8e2e-d5bca5b847a6.png)
</details>

**Comment by SudharakaP** [comment]
@pascalgrimaud : If have any further ideas on making UI improvements let us know. 😄

**Comment by ankitbeniwal** [comment]
@SudharakaP Is this fine?

![JHipster-UI-Improvements-by-Ankit-Beniwal](https://user-images.githubusercontent.com/12103073/96468355-a4b26780-1249-11eb-9a6d-48cc8061cb53.png)

**Comment by SudharakaP** [comment]
@ankitbeniwal : Yes that seems like a good improvement. 👍🏼
