### ISSUE TITLE
Can't get an activation link email

### ISSUE THREAD

**Issue by trblft** [jhipster/jhipster-online#24]
Hi,
I just tried twice to register on jhipster online.
I got a message telling me to check my email twice.
On the two emails I provided, no message received more than 30mn after registering.
Will this be fixed soon?
Have a nice day.

**Comment by jdubois** [comment]
Are you the person having a "@gmail.com.tr" email? Maigun says it's not a correct MX server so the problem is on your mail provider

**Comment by trblft** [comment]
Yes, that was me. It works now, but I did nothing, can't get the reason why it failed. Thanks anyway, have a nice day.

**Comment by jdubois** [comment]
Maybe it came from Mailgun, we have problems with them at the moment
