### ISSUE TITLE
Registration email not received

### ISSUE THREAD

**Issue by nashcrash** [jhipster/jhipster-online#25]
I signed up for junkster online with "nashcrash" account and my email, but I did not receive the registration email.
**Is there a way to request it again?**

If I try to log in with username and password entered at registration, it tells me "the user does not exist".
If I try to reset the password, it tells me that "the email does not exist".
If I try to re-register, it tells me "the user and the e-mail already exist".

I attach screenshots (covered to avoid spam).

![try to reregister](https://user-images.githubusercontent.com/2830024/34824309-3aa22f7c-f6ce-11e7-8666-7489562d2470.png)
![try to reset](https://user-images.githubusercontent.com/2830024/34824310-3abe720e-f6ce-11e7-8d7b-09e13a813786.png)

**Comment by jdubois** [comment]
That's because your email address is not validated yet.
Either validate it, or wait for 48 hours and it will be cleared up automatically.

**Comment by nashcrash** [comment]
Oh, sorry.
Oh sorry. I did not realize that I had to wait up to 48 hours...

Thanks for the reply.

"NashCrash"
nashcrash@sitissimo.it



2018-01-11 15:21 GMT+01:00 Julien Dubois <notifications@github.com>:

**Comment by jdubois** [comment]
Hang on, there's a problem with mailgun -> I'm solving that, I'll then send emails individually to everyone impacted
