### ISSUE TITLE
Can't register in JHipster Online Platform

### ISSUE THREAD

**Issue by dmartinvega** [jhipster/jhipster-online#26]
Hi!

I can't sign in to JHipster Online because the confirmation e-mail never arrived and when I try to sign in it says that I'm not registered yet but when I try to register again a warning says I'm already registered.

Thank you.

**Comment by jdubois** [comment]
Mailgun (our e-mail provider) was down for a couple of days, but yesterday I fixed it and sent all the missing e-mails - can you check?
Otherwise please give me your login name and I'll activate your account manually.

**Comment by dmartinvega** [comment]
I just checked and I didn't receive it.

My login name is dmartinvega and the e-mail address is dmartinvega@gmail.com

Thank you so much.

**Comment by jdubois** [comment]
Done :-)

**Comment by kawsurilu** [comment]
I also can't register. No email arrived. Username is kawsurilu

**Comment by jdubois** [comment]
Indeed, it looks like yahoo.com is now blacklisting our emails!! Bad news :-(

@kawsurilu I activated your account manually, so it should work for you.

**Comment by kawsurilu** [comment]
Yes, account is activated. 

@jdubois  Thanks a lot.
