### ISSUE TITLE
Console errors about Content Security Policy and missing image

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-online#261]
I see the following error in my console when I hit start.jhipster.tech without being logged in.

<img width="1577" alt="Screen Shot 2020-11-11 at 11 43 01 AM" src="https://user-images.githubusercontent.com/17892/98851425-791f3900-2413-11eb-9375-9c8e4c354fa5.png">

After logging in, there's a 404, but it looks like it's coming from 1Password, not from JHipster.

<img width="1577" alt="Screen Shot 2020-11-11 at 11 43 32 AM" src="https://user-images.githubusercontent.com/17892/98851532-a10e9c80-2413-11eb-9ea2-3c371cec38ae.png">

**Comment by SudharakaP** [comment]
@mraible : I tested with both Chrome and Firefox and I cannot see that security policy violation; although I do see a security policy violation related to google-analytics. My guess is that one might also be coming from a extension you've installed. Could you do this on an incognito window (assuming all extensions are disabled there) and show me the result? Thanks. 🤝

**Comment by mraible** [comment]
Here's an incognito screenshot. It is a bit different from the one I posted above.

<img width="1516" alt="Screen Shot 2020-11-11 at 7 38 29 PM" src="https://user-images.githubusercontent.com/17892/98888580-7c3b1900-2455-11eb-9747-a646d653b013.png">

I think we need to add a rule to the CSP to allow XHR (`connect-src`) connections to GA. Something like this:

```
connect-src 'self' https://www.google-analytics.com
```

**Comment by SudharakaP** [comment]
@mraible : Yes, now what you see is what I see on my side as well. I will create a PR for that. Thanks for verifying. 👍🏽

**Comment by SudharakaP** [comment]
@mraible : I've deployed a new version of jhipster-online; should be live in around 10 mins. That should solve this problem; let me know otherwise. 👍🏽
