### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Excalibure86** [jhipster/jhipster-online#27]
Hi,
I'm trying to register to jhipster online but i didn't get the confirmation mail to confirm it.
I used Gmail and my personnel domain name.

**Comment by jdubois** [comment]
Thanks so much -> it looks like Mailgun is having issues (again!!), I'm restarting the server, give me 2 minutes :-)

**Comment by jdubois** [comment]
It should be good now, and I have manually activated your account.

Thank you so much!

**Comment by Excalibure86** [comment]
Thank you , i have recieved my confirmation.

**Comment by jdubois** [comment]
Oh, did you still get an e-mail message from JHipster Online? (not the one I sent personally)
It must have been in a queue somewhere, but it doesn't even show up on the mailgun logs! Can you confirm this?
