### ISSUE TITLE
Add Support to Auto Update Copyright Headers

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/jhipster-online#276]
**Is your feature request related to a problem? Please describe.**

Updating copyright headers manually each year is time consuming. We could automate this in a GitHub action. 

**Describe the solution you'd like**

Automate updating copyright headers at the end of each year.

**Additional context**

Originally suggested by @pascalgrimaud at https://github.com/jhipster/jhipster-online/pull/271#issuecomment-754431861

**Comment by pascalgrimaud** [comment]
Ahaha in fact, I didn't explain well.
I talk about upgrading the application to the latest version of generator-jhipster, not the copyright :)

When you modified the generated files by adding copyright, you can have a lot of conflict when upgrading the application. That's what I wanted to say.

Anyway, your idea is good too :)

**Comment by SudharakaP** [comment]
> Ahaha in fact, I didn't explain well.
> I talk about upgrading the application to the latest version of generator-jhipster, not the copyright :)
> 
> When you modified the generated files by adding copyright, you can have a lot of conflict when upgrading the application. That's what I wanted to say.
> 
> Anyway, your idea is good too :)

Thanks much for the explanation; although now sure what we can do about the conflicts when upgrading. 🤔
