### ISSUE TITLE
Disable OIDC + AngularJS

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-online#28]
I just helped out someone who used https://start.jhipster.tech to create his project and he ran into this issue (OIDC is not implemented for AngularJS).  We have a special condition in the generator that handles adding AngularJS to the clientFramework list if not using OIDC ([client/prompts.js](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/prompts.js#L46-L50)), I'm not sure how jhipster-online handles this.

To Reproduce:
 - Choose OIDC auth
 - Choose AngularJS as the client framework
 - Clone the generated project, `yarn && bower install && gulp install`
 - Project will not display due to missing AuthServerProvider

To Fix:
 - Don't allow choice of AngularJS as clientFramework when OIDC auth is selected

**Comment by jdubois** [comment]
Thanks @ruddell - yes I just need to remove it from the options on the Angular form

**Comment by jdubois** [comment]
It's corrected in our master branch
