### ISSUE TITLE
Deployment to GCP Fails

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/jhipster-online#285]
**Describe the bug**

It seems that starting recently (starting on the v2.7.9) our deployment workflow fails with the follwoing error when trying to push the docker image.

```
denied: Token exchange failed for project '***'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
```

Sample build run: https://github.com/jhipster/jhipster-online/actions/runs/681223047

**To Reproduce**

1. Create a new deployment (needs to be admin of this repository)

**Expected behavior**

The docker image should be pushed successfully to GCP. Something might have changed maybe on the GCP side; v2.7.8 and before it was working correctly. 🤔

**Comment by PierreBesson** [comment]
I did a PR with @SudharakaP to migrate from container registry to artifact registry: https://github.com/jhipster/jhipster-online/pull/286

**Comment by pascalgrimaud** [comment]
Added a bounty as I know you're doing your bests to fix the release on JH Online

**Comment by SudharakaP** [comment]
I fixed the remaining errors, it was minor and the deployment works now as usual. 🥳 

@pascalgrimaud : Thanks. 😄 

@PierreBesson : Thanks a lot Pierre for helping me. I think you did the main work in migrating to artifact registry. So you should take the bounty. Cheers. 😄

**Comment by SudharakaP** [comment]
@pascalgrimaud : Bug bounty invoice submitted at https://opencollective.com/generator-jhipster/expenses/37159

@PierreBesson : Please claim the other half. Thanks for helping. 👍🏽

**Comment by pascalgrimaud** [comment]
@SudharakaP : approved

**Comment by SudharakaP** [comment]
> @SudharakaP : approved

Thanks 👍🏽

**Comment by PierreBesson** [comment]
I have claimed my bounty on opencollective: https://opencollective.com/generator-jhipster/expenses/37215

**Comment by pascalgrimaud** [comment]
@PierreBesson : approved
