### ISSUE TITLE
Monolithic application has @EnableDiscoveryClient in App

### ISSUE THREAD

**Issue by jarielpa** [jhipster/jhipster-online#29]

**Comment by ruddell** [comment]
@jarielpa This happens when you choose Yes to **Do you want to use the JHipster Registry to configure, monitor and scale your application?**

If you don't want to use the registry or Eureka, choose No

**Comment by jarielpa** [comment]
I did choose no, at least there was no maven dependency. Generated code could not compiled

Lähetetty iPhonesta

**Comment by ruddell** [comment]
Do you have a link to a Github repository showing the project you generated?  Or at least the config from your `.yo-rc.json`?

I generated a monolith with both Yes and No for JHipster Registry and they both compile without issue.

**Comment by jarielpa** [comment]
https://github.com/jarielpa/jhipsterSampleApplication.git

It is now not compiling because I was testing jdl stuff,.

{
"generator-jhipster": {
"applicationType": "monolith",
"gitHubOrganization": "jarielpa",
"baseName": "jhipsterSampleApplication",
"packageName": "io.puhos.jhipster.application",
"serverPort": 8080,
"serviceDiscoveryType": "false",
"authenticationType": "session",
"uaaBaseName": "../uaa",
"cacheProvider": "no",
"enableHibernateCache": false,
"websocket": false,
"databaseType": "sql",
"devDatabaseType": "h2Disk",
"prodDatabaseType": "postgresql",
"searchEngine": false,
"enableSwaggerCodegen": false,
"messageBroker": false,
"buildTool": "maven",
"enableSocialSignIn": false,
"useSass": false,
"clientPackageManager": "yarn",
"testFrameworks": [],
"enableTranslation": false,
"nativeLanguage": "en",
"languages": [
"en"
],
"clientFramework": "angularX",
"jhipsterVersion": "4.13.3",
"packageFolder": "io/puhos/jhipster/application",
"rememberMeKey": "335eccf2eacfd0e7871c6f411a29d1e125cbe365",
"jhiPrefix": "jhi"
}
}

**Comment by ruddell** [comment]
@jarielpa Thank you

@jdubois This looks like it is because of `    "serviceDiscoveryType": "false",` where false is a string instead of a boolean.  This happens if you select `Yes` and then change your mind and select `No` (on the JHipster Registry option).

**Comment by jdubois** [comment]
Thanks @ruddell I'll need to update this

**Comment by jdubois** [comment]
It's corrected in our master branch
