### ISSUE TITLE
Generate Application online has problem

### ISSUE THREAD

**Issue by Dado278** [jhipster/jhipster-online#294]
Hi all,

I generate application from
https://start.jhipster.tech/generate-application
and push it  in gitHub repository.
When a try to deploy it in Heroku server I get a maven error and build fails.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jh-sweet-home-dinner-application-2: Fatal error compiling: invalid target release: 11 -> [Help 1]

Besides, Table "JHI_USER" not found
and 
package tech.jhipster.web.util does not exist (this package is different from package generate few days ago)

Few days ago all works fine (with same steps),  does something has changed?
Thank you
Davide

**Comment by gmarziou** [comment]
It seems that you're deploying on java 8 runtime while having built for JDK 11.

**Comment by SudharakaP** [comment]
@Dado278 : Thanks for posting the issue; @gmarziou is correct. Normally Heroku by default supports Java 8 (https://devcenter.heroku.com/articles/java-support#supported-java-versions). So you need to set it to Java 11 as specified in that section. If you did use the [Heroku Sub-generator](https://www.jhipster.tech/heroku/#deploying-to-heroku) (which I assume you didn't?) we set this property automatically; https://github.com/jhipster/generator-jhipster/blob/662d82a391536f9639991e73e4219d8475ab164e/generators/heroku/templates/system.properties.ejs#L1

**Comment by Dado278** [comment]
Thank you @gmarziou and @SudharakaP , now it works correctly :)
Sorry for incorrect subject, I wanted to open it as white support ;)
Have a good day 💯

**Comment by SudharakaP** [comment]
> Thank you @gmarziou and @SudharakaP , now it works correctly :)
> Sorry for incorrect subject, I wanted to open it as white support ;)
> Have a good day 100

Thanks for the confirmation. Have a good day to you too. Let us know if you have any other questions. 😄
