### ISSUE TITLE
Connection refused when I try to modify data

### ISSUE THREAD

**Issue by Dado278** [jhipster/jhipster-online#295]
Hi all,
I generated jhipster application by online generator website
https://start.jhipster.tech/generate-application

Application is deployed on Heroku server online, it works, for example to read data from H2 DB, but when I try to modify data I get
Exception in createUser() with cause = 'java.lang.RuntimeException: Connection refused' and exception = 'Connection refused; nested exception is java.lang.RuntimeException: Connection refused'
2021-04-12T15:25:04.535044+00:00 app[web.1]: 
2021-04-12T15:25:04.535046+00:00 app[web.1]: org.springframework.dao.DataAccessResourceFailureException: Connection refused; nested exception is java.lang.RuntimeException: Connection refused

What's wrong?

Thank you
Davide

**Comment by pascalgrimaud** [comment]
Is it this project you tried to deploy to Heroku ?
https://github.com/Dado278/jh-sweet-home-dinner-rep2/blob/main/.yo-rc.json#L16

In this case, you need to use PostgreSQL, which is free. Otherwise, you need to configure your Heroku account to have MySQL database, if I'm not wrong

**Comment by Dado278** [comment]
Hi @pascalgrimaud,
yes, that's my repository, I configured MySQL only for production and H2 DB with hard disk persistence, I expected that Heroku use H2 DB.
With "jhipsterVersion": "6.10.5", repository with MySQL and H2 DB
https://github.com/Dado278/jh-sweet-home-dinner-rep/blob/main/.yo-rc.json 
it works correctly.

With "jhipsterVersion": "7.0.1", actual repository
I get exception.

What is it changed?

Thank you for your support, 
Davide

**Comment by pascalgrimaud** [comment]
Once you deploy to Heroku, it will use `prod` profile:
- you need to have an Instance of MySQL, running in your Heroku account
- as you choose Elasticsearch, it's the same -> https://github.com/Dado278/jh-sweet-home-dinner-rep/blob/main/.yo-rc.json#L17 -> you need to have an instance of Elasticsearch

The error is normal: `org.springframework.dao.DataAccessResourceFailureException: Connection refused; nested exception is java.lang.RuntimeException: Connection refused` as you don't have these services running, so your application can't work automatically on Heroku, unless you configured these services.

The best way to try Heroku is:
- create an application, using PostgreSQL (the instance is free)
- don't choose Elasticsearch
- so it will easier to deploy to Heroku

**Comment by Dado278** [comment]
Hi @pascalgrimaud,
thank you for your explanation and hint, I'm new about JHipster ;)
Now it works correctly :)
I will close this thread.
Have a good day,
Davide
