### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by GLLeague** [jhipster/jhipster-online#30]
Hi,

probably I have the same problem with registration - #27 

I'm trying to register to jhipster online but i didn't get the confirmation mail to confirm it.
I used Gmail and my personnel domain name.

**Comment by jdubois** [comment]
Thanks! I hope that's not broken again :-(
Let me check

**Comment by jdubois** [comment]
Thanks a lot, that's clearly broken. We have hundreds of people who registered and are blocked, you're the first one to a ticket, thanks a lot!!!

**Comment by jdubois** [comment]
I'm activating every user manually and will send everyone an email when it's done - of course we have something like 200 new users in the last 2 days, so that will take some time :-(

**Comment by jdubois** [comment]
Done :-)
Thanks so much @GLLeague
