### ISSUE TITLE
Release v7.1.0

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-online#303]
I think we can upgrade to v7.1.0.
Do you confirm @jdubois ?

cc @SudharakaP

**Comment by jdubois** [comment]
Ah yes, please do! Thank you!

**Comment by SudharakaP** [comment]
> I think we can upgrade to v7.1.0.
> Do you confirm @jdubois ?
> 
> cc @SudharakaP

Will do this over the weekend. 😄

**Comment by pascalgrimaud** [comment]
@SudharakaP : is it similar to https://github.com/jhipster/jhipster-online/pull/293/ ? if yes, I can prepare the PR

**Comment by SudharakaP** [comment]
@pascalgrimaud : Yes, exactly similar. 👍🏽
