### ISSUE TITLE
Get "Create Application" form on homepage with a compact UI

### ISSUE THREAD

**Issue by swarajsaaj** [jhipster/jhipster-online#305]
With https://github.com/jhipster/jhipster-online/pull/301 now anonymous users can generate the application. 
It would be nice to have this form on the homepage of start.jhipster.tech, with a compact UI (maybe something similar to https://start.spring.io or https://micronaut.io/launch/, ideas welcome :) )

**Comment by SudharakaP** [comment]
My personal thinking on this matter is that the application generation form is too large to just embed in the front page. Note that both spring and micronaut is different in that they don't let user to register or sign in at all. We provide more capabilities such as signing in and saving the jdl templates creating the repos on GitHub, GitLab etc. 

Therefore I don't quite agree with just having this form on the front-page. However what we could do is to have a similar card as the register or sign in card; 

![image](https://user-images.githubusercontent.com/12435965/123524553-fa180180-d67f-11eb-8d3b-b7e1d91d3cdb.png)

for creating the application as a guest. This can be below the two existing cards and centred. But let us wait for others feedback as well.

cc: @pascalgrimaud @jhipster/developers

**Comment by PierreBesson** [comment]
I also agree with this idea of adding a "generate app" card. It could even be the first card presented. Then we could add a short message explaining the advantages of using a registered account such as "registered users can save their application configurations / entities and upload their apps directly to GitHub/Gitlab".

**Comment by SudharakaP** [comment]
@PierreBesson : Thanks for the idea. Yes I agree we could make it the first card. 

@swarajsaaj : Feel free to submit a PR if you like. The card design should mimic what we have to register and Sign In cards. But the button can be, `Generate App` or `Create Application`. And the description can be something like what @PierreBesson mentioned above. 😄

**Comment by swarajsaaj** [comment]
Thanks for the ideas @SudharakaP , @PierreBesson  😄 
Yes I agree, we do more than just zip file downloads after login and these features shall be highlighted appropriately, I will work on adding the card with description.
Additionally, as you mentioned the form is too large (even on the dedicated page), hence we can think to redesign it to a "compact" interface, reducing scroll and number of clicks. What do you suggest about that?

**Comment by SudharakaP** [comment]
> Additionally, as you mentioned the form is too large (even on the dedicated page), hence we can think to redesign it to a "compact" interface, reducing scroll and number of clicks. What do you suggest about that?

My thinking is that the form is fine on the dedicated page and I am doubtful on changing it to a smaller design. The users should ideally see all the options offered by the generator and having those in the form isn't necessarily a drawback. However this is just my opinion, and if you feel it's something to be discussed feel free to open a new issue so that the team could weight on it. 😄
