### ISSUE TITLE
Configure JHipster Online to access my GitHub account FAILS

### ISSUE THREAD

**Issue by fredusername** [jhipster/jhipster-online#31]
1. I click on ``Authorize JHipster" within Github
2. JHipster appears in Authorized OAuth Apps
3. Back to JHipster, I get ``  Warning! To generate your application on GitHub, you must authorize JHipster"
4. I click on ``Authorize JHipster" within Github
5. Back to (1.)

**Comment by jdubois** [comment]
Where do you see that step 1, "authorize JHipster" within GitHub?

**Comment by fredusername** [comment]
Got it

It’s a Safari problem. Works fine with Chrome under MacOS

+F

**Comment by jdubois** [comment]
OK it's interesting to know - I'll try to reproduce
