### ISSUE TITLE
Dev containers are exposing ports on non localhost IPs

### ISSUE THREAD

**Issue by nomuna** [jhipster/jhipster-online#317]
The provided compose yml files create containers that open ports to the public.

Related (closed) issue from generator-jhipster: https://github.com/jhipster/generator-jhipster/issues/12015

**Comment by SudharakaP** [comment]
@nomuna : I believe this is not longer relevant as jhipster-online has been upgraded to use jhipster-generator 7.9.3 which includes the aforementioned fix. Correct me if I am wrong please.
