### ISSUE TITLE
Ports in sonar-project.properties and sonar.yml don't match

### ISSUE THREAD

**Issue by nomuna** [jhipster/jhipster-online#318]
Port in _sonar-project.properties_ is 9001
Port in _src/main/docker/sonar.yml_ is 9000

**Comment by somayaj** [comment]
Hi, can this be worked?

**Comment by SudharakaP** [comment]
@nomuna : I am a bit confused with this one; the host port is 9001 and is mapped to the default sonar port 9000 of the container. And in the `sonar-project.properties` the port should be 9001 as it should map the host port not the port within the container. If you think differently please feel free to comment and re-open the issue.
