### ISSUE TITLE
start create jhispter service issue

### ISSUE THREAD

**Issue by wp-jackliu** [jhipster/jhipster-online#319]
**Describe the bug**
website: https://start.jhipster.tech/generate-application
action : type any message on the form

click  Download as Zip file  
**_**the zip file only contain a .yo-rc.json file.**_**

**Comment by wp-jackliu** [comment]
![image](https://user-images.githubusercontent.com/3220935/133758591-5e6ea4e1-122d-4bbc-b454-3c1d8efbfa2a.png)

**Comment by pascalgrimaud** [comment]
Thanks for reporting this, @wp-jackliu 

I think there is a problem with Yarn version.
How can we fix this, @SudharakaP ?

**Comment by jdubois** [comment]
I've had a look at the logs and that seems indeed linked with Yarn doing a Git a command:

```
log `d1ffb2b1-5d5a-4ddd-b9fc-a4c144fa7c29` :     at PluginStore.exec (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)
log `d1ffb2b1-5d5a-4ddd-b9fc-a4c144fa7c29` :     at /usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45
```

I didn't know we were still using Yarn somewhere here! Calling also @PierreBesson for help here

**Comment by pascalgrimaud** [comment]
@jdubois : it can be a problem with Node version. Can you check if we use a LTS version, specially 14.17.6 ?

**Comment by jdubois** [comment]
Here what I have inside the container (in production):

```
root@9a614ec10d58:/# java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
root@9a614ec10d58:/# node --version
v14.17.6
root@9a614ec10d58:/# yarn -version
1.22.5
root@9a614ec10d58:/#

**Comment by jdubois** [comment]
Oh I can reproduce the error inside the container, by running "jhipster" on the console:

```
? Please choose additional languages to install 
ERROR! Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
GitError: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at Object.action (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/plugins/error-detection.plugin.js:30:33)
    at PluginStore.exec (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/plugins/plugin-store.js:21:33)
    at /usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:95:45
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:93:16)
    at GitExecutorChain.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:77:46)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/share/.config/yarn/global/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58) {
  task: {
    commands: [ 'rev-parse', '--is-inside-work-tree' ],
    format: 'utf-8',
    onError: [Function: onError],
    parser: [Function: parser]
  }
}

**Comment by jdubois** [comment]
Argh "git" isn't install in the container!!!! WTF?

**Comment by jdubois** [comment]
I guess all we need to do is install git in https://github.com/jhipster/jhipster-online/blob/main/Dockerfile as someone removed it from the main image

**Comment by jdubois** [comment]
- I fixed the production container manually -> it's currently running OK but that's obviously not a good solution at all
- The issue was that Git wasn't installed: it looks to me that an `apt-get update` failed when creating the container, so I would first just try to build a new one
- Otherwise, the solution is to do an `apt-get install git`

Unfortunately I'm not the best person to update this - I'm ready to help if needed, of course.

**Comment by pascalgrimaud** [comment]
Ok thanks @jdubois : I'll have a look after lunch to try to fix this properly

**Comment by mshima** [comment]
jhipster-online should extend generator-jhipster image instead of creating its own from the ground.

**Comment by SudharakaP** [comment]
Thanks for looking into this everyone. Sorry I was a bit busy over the past couple of weeks. But I just deployed the fix by @mshima to this so now it should all be good and working. Therefore I am closing this one. 👍🏽
