### ISSUE TITLE
Add a "Power by GCP" footer

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-online#344]
As Google provides us credits to host JHipster Online, we should thank them with a specific footer, like "Powered by Google Cloud Platform".
@alexismp should be able to validate the exact wording and maybe add a logo (I'm not sure we can do this without signing some document, I'll do this if that's necessary)

**Comment by alexismp** [comment]
"Powered by Google Cloud" with this logo would be great, thanks : https://www.gstatic.com/devrel-devsite/prod/v870be6fb6841f3532cd3aec5bc0b3146031642f2794ae8ba7f51ebf843a655f9/cloud/images/cloud-logo.svg

**Comment by jdubois** [comment]
As the logo itself says "Google Cloud", this is making "Powered by Google Cloud Google Cloud", so I just put "Powered by" + logo.
I'll put a screenshot in the PR so you can have a look.
