### ISSUE TITLE
CloudProviding JHipster-lite application

### ISSUE THREAD

**Issue by matthieulapatate** [jhipster/jhipster-online#349]
The idea would be to host the application on cloud in order to permit the application to be accessible everyone by everyone.

In a first hand, i would like to deploy the application on a simple Heroku server, kind of staging website in tests the new front-end fonctionnalities. The server will generate the asked files locally on the server and then when the user will ask for it, he will receive a zip file withs all the files in it.

After this will be done, we will need to think about the way to implement the application with security part because the problem coming with this method is that everyone will be able to spam the generation part and break the server.

The work will be done on the branch "CloudProviding" and the application will be available at :https://jhipsterlite.herokuapp.com/

**Comment by pascalgrimaud** [comment]
@matthieulapatate : why are you creating this ticket in JHipster Online project? I think you're wrong as it's not the scope of this project

**Comment by matthieulapatate** [comment]
Sorry wrong project.
