### ISSUE TITLE
GitHub Access Issue for online project creation

### ISSUE THREAD

**Issue by eshaprasadts** [jhipster/jhipster-online#38]
Even after giving access & confirming the access using GitHub alert email, the Online Application Creation is not recognizing the link and behaves as though access is not provided.

**Comment by jdubois** [comment]
I'm sorry I don't get the "GitHub email alert" part, do you mean you clicked on https://start.jhipster.tech/#/github and then get some error when generating the application on GitHub? Could you give your username I'll have a look in the logs.

**Comment by eshaprasadts** [comment]
Hi,  I am still seeing    "Warning! To generate your application on GitHub, you must authorize JHipster Online to access your GitHub account. You will only be able to download your application as a Zip file" even if I have given permission.  
FYI: 
![git_access](https://user-images.githubusercontent.com/29681595/39660072-3bd9a248-4ffd-11e8-9f49-e2d5b1679b5c.png)

**Comment by jdubois** [comment]
Oh thanks, there must be a regression following yesterday's migration - not sure what this is as I don't remember changing anything there.
I'll update the ticket when it's corrected, hopefully very soon.

**Comment by mmanrai** [comment]
FYI... I am having the exact same issue. I have authorised jHipster to access my GitHub account. If i login to my GitHub account, I can see that the access has been granted. However, JHipsterOnline thinks that my GitHub account is not linked and shows me following message "JHipster is not linked to your GitHub repository."

**Comment by jdubois** [comment]
Thanks a lot, that's really weird. Can you give me your username? Not sure I can fix this during the weekend

**Comment by jdubois** [comment]
OK I found the bug, it's my fault!! A bad search & replace command!
Thanks a lot @eshaprasadts @mmanrai for reporting this issue!

Not sure when I'll have time to correct, but that will only take me 5 minutes :-)

**Comment by mmanrai** [comment]
Cheers!

**Comment by jdubois** [comment]
This should be fixed now, can you @eshaprasadts @mmanrai could you do a test? Sorry for that issue!

**Comment by jdubois** [comment]
Closing the ticket - I see people generating projects successfully on GitHub, so I know it works!
