### ISSUE TITLE
dead "JDL" link

### ISSUE THREAD

**Issue by danielpaukowitsch** [jhipster/jhipster-online#382]
**Describe the bug**
Dead/old link on "Design Entities" - list page.  
old/dead link: https://www.jhipster.tech/jdl/
correct link: https://www.jhipster.tech/jdl/intro

**To Reproduce**
1. Go to 'https://start.jhipster.tech/'
2. Sign in
3. Go to 'https://start.jhipster.tech/design-entities'
4. Click on '[JHipster Domain Language (JDL)](https://www.jhipster.tech/jdl/)'
5. See error

**Comment by SudharakaP** [comment]
I don't see an issue with this. When you go to https://www.jhipster.tech/jdl/ it automatically goes to the first page of that section; https://www.jhipster.tech/jdl/intro (see screen-cast below). 

[link-jhipster-online.webm](https://github.com/jhipster/jhipster-online/assets/12435965/c95cbecf-aea4-4b8e-a4b0-ec3442257257)

@danielpaukowitsch : If you see an error please attach a screenshot so we can investigate further.
