### ISSUE TITLE
Project generated failed with generator-jhipster-azure-spring-apps blueprint

### ISSUE THREAD

**Issue by fangjian0423** [jhipster/jhipster-online#402]
**Describe the bug**

Follow https://github.com/Azure/generator-jhipster-azure-spring-apps/issues/2, the project generated with `generator-jhipster-azure-spring-apps` blueprint is not as expected.

**To Reproduce**

JHipster Online will generate .yo-rc.json in temp directory, then run `jhipster --force-insight --skip-checks --skip-install --skip-cache --skip-git` command to generate project.

To make the steps simple, use following steps to reproduce the issue:

1. Create .yo-rc.json in temp directory,  below is the content:

```json
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "jhipsterSampleApplication",
    "blueprints": [
      {
        "name": "generator-jhipster-azure-spring-apps",
        "version": "1.0.12"
      }
    ],
    "buildTool": "maven",
    "cacheProvider": "no",
    "clientFramework": "react",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1690376815863,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "devServerPort": 9060,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "entities": [],
    "entitySuffix": "",
    "gitCompany": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "8.0.0-beta.2",
    "jwtSecretKey": "YjE1MWZlNWM1ZWFkYWEyODZjZmNkZDQ3ODE5NzJkMGU0MmM2ZGFkNmZhNjhhOTEyM2FmZTdhYmE3ZDBkNjYyMzFlMmUxNWExZmY5MmE1ZTlkYTA3ODE5YTAyMDkxMTRjNGIxN2EwMDc3ZmQ5NWY5Y2I1OTRkMmQxZmY3ZGQzMzQ=",
    "languages": ["en"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "postgresql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": 8080,
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipClient": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "useSass": true,
    "websocket": false,
    "withAdminUi": true
  }
}
```

2. Run `jhipster --force-insight --skip-checks --skip-install --skip-cache --skip-git` command.

**Expected behavior**

Generate Todo apps by `generator-jhipster-azure-spring-apps` blueprint, but it doesn't.  We get IOException because the command will prompt to overwrite files.

**Screenshots**

![image](https://github.com/jhipster/jhipster-online/assets/5254035/e7e50e45-f491-43fb-b3d6-53f5521e5faa)

**Desktop (please complete the following information):**

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

git version 2.25.1

node: v18.17.0
npm: 9.6.7

**Additional context**

**Comment by jdubois** [comment]
Maybe you can add `--force` to the JHipster command line

**Comment by fangjian0423** [comment]
I added `--force`, it generated project successful, but some files not belong to generator-jhipster-azure-spring-apps blueprint generated.

![image](https://github.com/jhipster/jhipster-online/assets/5254035/fdee5310-ca46-4ce3-90bb-05a70864dfd0)

**Comment by fangjian0423** [comment]
Fixed by https://github.com/jhipster/jhipster-online/pull/403.
