### ISSUE TITLE
Not able to login to Jhipster Online

### ISSUE THREAD

**Issue by jcm-altia** [jhipster/jhipster-online#42]
Hello,

I have registered the user jcm-altia with my email address, but neither received confirmation email, nor able to login. New attempt to register throws error (login already in use, email address already in use).

Can you please check?

**Comment by jdubois** [comment]
Checking right now

**Comment by jdubois** [comment]
- e-mails seems to be sent OK
- when did you create your account? I'm trying to find it

**Comment by jdubois** [comment]
Oh I got your account, it's indeed not activated, let me check why

**Comment by jdubois** [comment]
According to Mailgun you did correctly receive the activation email, there shouldn't be any problem at all.
I'm activating it manually, so it's all OK.
