### ISSUE TITLE
Allow GitHub repo and application name to be different

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-online#43]
When I created my [jhipster4-demo](https://github.com/mraible/jhipster4-demo), I used "blog" for the name and "jhipster4-demo" for the repository name. It'd be awesome if I could do the same with JHipster online.

**Comment by chrisdns** [comment]
We just added the feature, it should be merged soon with the GitLab support

**Comment by jdubois** [comment]
It's already merged so I'm closing this.
