### ISSUE TITLE
Register email confirmation never made its way to my inbox

### ISSUE THREAD

**Issue by jotamorais** [jhipster/jhipster-online#5]
I registered with my email and it said I would receive an email and I had to confirm it but I never got any.

**Comment by jdubois** [comment]
Thanks Jonathan, I do see in the mailgun logs that you received the email -
maybe it's in your spam folder?

Le 28 juil. 2017 6:49 PM, "Jonathas Morais" <notifications@github.com> a
écrit :

**Comment by jotamorais** [comment]
@jdubois,  I got it now. It wasn't in my spam - just took a long time to be delivered (perhaps something with your SMTP/Mail hub - just guessing).

But thanks anyway!

**Comment by mfreed420** [comment]
I can't seem to register.  Maybe I've been on my computer too many hours.
