### ISSUE TITLE
can't get account to register

### ISSUE THREAD

**Issue by mfreed420** [jhipster/jhipster-online#6]
I can't seem to register. Maybe I've been on my computer too many hours. wait I register the account then I confirm email in my spam then when I go log in it says account cannot be confirmed. I have tried changing password multiple times. I have a capital letter small case letter a number and a symbol in my password. Any advice on how I may register or what I may be doing wrong?  

The error message reads as follows: Failed to sign in! Please check your credentials and try again.

**Comment by jdubois** [comment]
Our UX is bad here (and it's the default JHipster UX, so that's really bad) - did you use your login or your email to log in? Of course you need your login.

**Comment by mfreed420** [comment]
I  believe I used my email I think.




-----Original Message-----

**Comment by mfreed420** [comment]
That worked using my login and not my email.  Thank you!!!

**Comment by jdubois** [comment]
We need to change the UX
