### ISSUE TITLE
Unable to reset my password

### ISSUE THREAD

**Issue by mlstoppa** [jhipster/jhipster-online#62]
Hello,
I am trying to reset my login's password but when I click on "Did you forget your password?" button it says "Emails are disabled on this server! You will need to ask an administrator to provide you a password reset link."
My login name is mlstoppa, and I am sure it exists because I can't register again with the same login credentials.
Can you help me?
Thank you

**Comment by jdubois** [comment]
Oh that's a bug! @chrisdns @agaspardcilia can you have a look?

**Comment by pascalgrimaud** [comment]
Maybe it's this property `jhipster.mail.enabled` is missing for prod profile.

See in dev, it's active https://github.com/jhipster/jhipster-online/blob/master/src/main/resources/config/application-dev.yml#L116

In prod, it's missing: https://github.com/jhipster/jhipster-online/blob/master/src/main/resources/config/application-prod.yml#L108-L110

@jdubois : do you want me to PR to change this config to true, or do you prefer to override it, directly in production ?

**Comment by agaspardcilia** [comment]
Yes, it's probably just a configuration issue.

**Comment by jdubois** [comment]
Oh I can try it in prod - I'm with my phone, but I like to live dangerously:-)

**Comment by jdubois** [comment]
Can you test now ? I'll have a look tomorrow

**Comment by pascalgrimaud** [comment]
It works. Thanks @jdubois !
Seriously, with your phone lol...
