### ISSUE TITLE
Never received activation mail

### ISSUE THREAD

**Issue by brunomendola** [jhipster/jhipster-online#66]
Hi, I registered a few days ago (with the same username as in Github) and I never received the activation mail.

The site doesn't let me register with the same mail, so I know I entered it correctly.

Login and Reset password don't work and there is no way to resend the activation mail.

Please, could you activate my account?

Maybe there is a problem sending to Hotmail/Outlook.com?

Is the "resend activation mail" feature in the roadmap?

Many thanks!

**Comment by jdubois** [comment]
Hi, I did find your username: you registered 2 days ago in the afternoon... the registration links gets deleted every 2 days if it's not used, so if you missed the registration email you'll be able to create a new account tomorrow. 
If you still don't get it, maybe it's an issue with your email provider which is black listed (typically for spam). Just ask me again and I'll activate it manually (but I'm on my phone, on holidays, so it can take some time).

**Comment by brunomendola** [comment]
Hi @jdubois , 

please, 2 days have passed and I still can't login nor register:

- login fails "Failed to sign in! Please check your credentials and try again."
- reset password says "Email address isn't registered! Please check and try again."
- registration says "Email is already in use! Please choose another one."

Thank you.

**Comment by jdubois** [comment]
Yes that was all because your email wasn't validated yet - I'm not sure why it wasn't deleted, I will check that.
Anyway, I validated it manually, you should be able to log in.

**Comment by brunomendola** [comment]
Thank you!
