### ISSUE TITLE
Git Providers Loading Issue on Generate App page

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-online#76]
Navigating directly to the `generate-application` route (https://start.jhipster.tech/#/generate-application) and logging in results in an error message: `There is no Git provider available, please contact your administrator to configure one. You will only be able to download your application as a Zip file.` Refreshing the page fixes this

[Screenshot](https://user-images.githubusercontent.com/4294623/44422876-412d3200-a539-11e8-9414-55983cbe3512.png)

**Comment by jdubois** [comment]
Thanks @ruddell - please note that you should not be automatically logged in using "remember me" in order to get the bug (I took some time to understand!)

**Comment by agaspardcilia** [comment]
I'll try to PR something about it this week end.
