### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/jhipster-online#8]
![image](https://user-images.githubusercontent.com/11784253/29065581-316b7f98-7c4a-11e7-8789-3a4024c15e86.png)

**Comment by jdubois** [comment]
I just tried it without any issue - maybe a network issue? Can you try again?

**Comment by JinnaBalu** [comment]
i have registered with jinnabalu24@gmail.com, it worked, but when i clicked for reset password it is not working. I am justing testing the flows.

**Comment by JinnaBalu** [comment]
https://github.com/JinnaBalu/sampleJhOnline/blob/master/.yo-rc.json, 
i have created aplicatuon with cassandra and elasticsearch together, bydefault which is not allowed when i create app  yo. 

Is this working with latest release?

**Comment by jdubois** [comment]
No this shouldn't work. Anyway nobody uses Cassandra, so we can't test advanced options with Cassandra
