### ISSUE TITLE
Gitlab CI support

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-online#80]
Currently the CI/CD can only generate Travis/Jenkins Configuration. It would be cool to have it also generate gitlab ci configuration. What do you think?

**Comment by jdubois** [comment]
Yes of course. Main issue for me is that it needs to run only with flags (no questions asked by the generator, or they will block the generation). Is that already the case?

**Comment by angeliski** [comment]
Hey @jdubois I can add A option `autoconfigure-gitlab` in the **generator-jhipster** and after update the **jhipster-online**, what do you think?

**Comment by jdubois** [comment]
@angeliski not sure of what you mean, but yes if you can run the sub-generator without any prompts, then it's very easy to add to JHipster Online

**Comment by angeliski** [comment]
Sorry @jdubois, I meaning if I can do a PR to improve that in the project. 
First I could make a PR to add the autoconfigure in generator, after another PR to add the option in that project. What do you think?

**Comment by agaspardcilia** [comment]
@angeliski Sure, the current configuration was generated by JHipster Online itself, it's quiet generic so if you have any suggestion about it any PR is welcome.

**Comment by pascalgrimaud** [comment]
@angeliski : if you decide to add gitlab to jhipster-online, can you consider adding azure pipelines too plz ?
See https://github.com/jhipster/generator-jhipster/pull/8478 as soon as it's merged

**Comment by angeliski** [comment]
Sure @pascalgrimaud when it's merged I will open a PR

**Comment by pascalgrimaud** [comment]
So nice ! My PR has been merged by @atomfrede !
