### ISSUE TITLE
Verification email not received when I tried to create an account on JHipster Online

### ISSUE THREAD

**Issue by QuentinFombaron** [jhipster/jhipster-online#81]
No email received when creating an account on JHipster Online.
I tried to create 2 different accounts but I received nothing to activate my account so I'm not able to sign-in.

The good email (**TO ACTIVATE**) : _q.fombaron@outlook.fr_
The second account to test (**TO IGNORE**) : _q.fombaron@hotmail.fr_

Thank you very much!

**Comment by jdubois** [comment]
Yes sorry about this, Outlook and Hotmail block our emails. I need to check
with Mailgun support, it's their fault in fact.
I'll activate your account manually, and close this ticket when it's done.

**Comment by jdubois** [comment]
Should be good, otherwise please add a comment

**Comment by QuentinFombaron** [comment]
I works thank you very much! 👍
