### ISSUE TITLE
Cannot use Application Generator

### ISSUE THREAD

**Issue by andyrewwer** [jhipster/jhipster-online#9]
After authorizing Jhipster in settings

<img width="744" alt="screenshot 2017-08-12 11 05 07" src="https://user-images.githubusercontent.com/5366359/29243187-279cd5aa-7f4e-11e7-9794-5f83ce1f9444.png">

I cannot generate an application, (this screen: 
<img width="699" alt="screenshot 2017-08-12 11 05 48" src="https://user-images.githubusercontent.com/5366359/29243189-3afcf076-7f4e-11e7-9ce9-ce2ef6375771.png">

When I try to authorize it again I see this page: http://jhipster.julien-dubois.com/#/github/callback/395efcab55a429847590 and the text `EOF`

**Comment by jdubois** [comment]
There might be a glitch in GitHub's OAuth2 server, could you try again tomorrow ? Hundreds of people used this, so under normal conditions this works.

**Comment by jdubois** [comment]
No news, and we still have many people using the app, so closing this.
