### ISSUE TITLE
Add ability to choose a module/blueprint when generating the app

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-online#90]
It would be nice to be able to generate a Kotlin or Vue.js project directly from start.jhipster.tech, especially for demos!

I don't know if we can have a list of all the available module/blueprints like the CLI generator proposes it.

An other solution could be to have a input text `Additional options` in a new category `Advanced configuration` given to the `jhipster` command when generating the app, we would be able to run with a blueprint orwithout user management,...
For instance imagine `--jhi-prefix dummy --blueprint kotlin --skip-user-management --yarn`

**Comment by pascalgrimaud** [comment]
It would be cool I think it is not possible.
In fact, each blueprint will have their own options, own questions and jhipster-online can't know in advance these options.

**Comment by deepu105** [comment]
Ya the only reliable way would be to provide an advanced generation page
which emulates a tty console where you can do some curated command line
actions(like the console from gcp for example) but that would be lot of
work I imagine

**Comment by hdurix** [comment]
Yes I reckon that it won't be easy to integrate them, maybe we should close this issue :)

**Comment by pascalgrimaud** [comment]
Let's close this.
