### ISSUE TITLE
JDL Studio <unique> keyword breaks the diagram sync

### ISSUE THREAD

**Issue by Belkacem** [jhipster/jhipster-online#92]
When using the unique keyword in jdl studio, the diagram will break here's the error in the console : 

`
Uncaught Error: MismatchedTokenException: Expecting token of type --> NAME <-- but found --> '}' <--
	at line: 36, column: 1
	at line: 36, column: 1
`

at Line 36 : 

`
entity Type {
  type String required,
  code Integer required unique
}
`

**Comment by murdos** [comment]
Existing issue on JDL Studio: https://github.com/jhipster/jdl-studio/issues/60
