### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by jnloga** [jhipster/jhipster-online#94]
Hello,
Il have create an account but i never receive the email for validation.
I try with another email, and have the same problem.
can you help please?
Thanks
Regards

**Comment by jnloga** [comment]
my username is jnloga (hotmail) and jgnloga (gmail).
problem with email confirmation.

**Comment by jdubois** [comment]
You are correct, let me fix that!

**Comment by jdubois** [comment]
Done, thanks a lot!!!!
