### ISSUE TITLE
Couldn't register

### ISSUE THREAD

**Issue by SheelaKumar** [jhipster/jhipster-online#97]
Hi!

I can't sign in to JHipster Online because the confirmation e-mail never arrived and when I try to sign in it says that I'm not registered yet but when I try to register again a warning says I'm already registered.

Thank you.

**Comment by jdubois** [comment]
Hi!
Looking at the logs you should have received the email (at least it reached your email provider!). Anyway, no worries: I activated your account manually.
Cheers,
Julien

**Comment by deepu105** [comment]
Julien may be we can think of using another email service (may be paid with
OC money) that doesn't get blocked by some email providers

**Comment by jdubois** [comment]
Here it was probably lost in the spam folder.
Biggest issue is that outlook and hotmail are blocked (not the case here), but most importantly is that I have no time to check the issue wth Mailgun.
