### ISSUE TITLE
Cannot registration on site https://start.jhipster.tech/

### ISSUE THREAD

**Issue by galants** [jhipster/jhipster-online#99]
I try to register on site https://start.jhipster.tech/, but I'm not receiving an email.
When I reset my password, I get the wrong message "Email address isn't registered!".
But if I try to register on site, again. I give a message "Email is already in use!"

**Comment by jdubois** [comment]
Thanks @galants - it's not your fault, we've had an issue for months with Mailgun not being able to send email to hotmail addresses.... so indeed you never got the message... So on the system the address is already in used, but not validated.

Anyway, I activated it manually, so it's good for you :-)

**Comment by deepu105** [comment]
Lets switch to another service using open collective funds if required

**Comment by jdubois** [comment]
@deepu105 we could take a "pro" account at Mailgun, but this costs 79$ per month, I find it very expensive, just for a few people. It will be the easiest way of solving the issue.

**Comment by jdubois** [comment]
Or we could remove the required email verification step. I'm using it for 2 reasons:

- reduce the number of spam account, but that's not a big issue in fact, as they can't do any real harm anyway
- protect people's data, as if you use a fake email account you can easily get hacked (trust me, I have a very common name, so many people use my email address.... even with their credit card attached to their account!). Then if people don't care about their data, it's also their own issue (at least Amazon and Uber don't do those checks.... those are the services where I had access to other people's credit cards....)

**Comment by pascalgrimaud** [comment]
Isn't possible to use GMail ?

**Comment by jdubois** [comment]
You don't have access to port 25 from GCP. So you need an external API provider that will send the emails for you.
